sudo: required
language: node_js

# The node.js version to install
node_js: "0.10.36"

install:
  # Install meteor
  - "curl https://install.meteor.com | /bin/sh"
  # Install spacejam
  - "npm install -g spacejam"

script:
  - "spacejam test-packages ./"
